/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-background": "#191c1c",
        error: "#ba1a1a",
        background: "#f9f9f8",
        surface: "#f9f9f8",
        "tertiary-fixed": "#c7f24b",
        "primary-container": "#063b00",
        "on-primary": "#ffffff",
        tertiary: "#172000",
        "tertiary-container": "#293700",
        "outline-variant": "#c1c9ba",
        "error-container": "#ffdad6",
        "surface-container": "#edeeed",
        secondary: "#2f6b19",
        primary: "#022300",
        "on-tertiary-container": "#82a700",
        outline: "#72796c",
        "primary-fixed": "#b8f2a2",
        "on-error-container": "#93000a",
        "inverse-primary": "#9cd588",
        "on-secondary-container": "#35721f",
        "on-secondary": "#ffffff",
        "on-surface": "#191c1c",
        "surface-bright": "#f9f9f8",
        "surface-container-highest": "#e1e3e2",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed-variant": "#1f5113",
        "surface-variant": "#e1e3e2",
        "secondary-fixed": "#b0f591",
        "secondary-fixed-dim": "#95d878",
        "on-tertiary-fixed-variant": "#3b4d00",
        "surface-dim": "#d9dad9",
        "on-tertiary": "#ffffff",
        "on-primary-container": "#71a85f",
        "secondary-container": "#b0f591",
        "on-secondary-fixed-variant": "#165200",
        "on-tertiary-fixed": "#161f00",
        "tertiary-fixed-dim": "#abd52e",
        "on-error": "#ffffff",
        "surface-container-low": "#f3f4f3",
        "inverse-surface": "#2e3131",
        "on-primary-fixed": "#022100",
        "on-secondary-fixed": "#052100",
        "surface-container-high": "#e7e8e7",
        "primary-fixed-dim": "#9cd588",
        "surface-tint": "#376a29",
        "inverse-on-surface": "#f0f1f0",
        "on-surface-variant": "#42493d",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "container-max": "1280px",
        base: "8px",
        xl: "80px",
        gutter: "24px",
        lg: "48px",
        sm: "12px",
        xs: "4px",
        md: "24px",
      },
       fontFamily: {
        sans: ["Inter"],
        "headline-md": ["Inter"],
        "display-lg": ["Inter"],
        "body-lg": ["Inter"],
        "label-sm": ["Inter"],
        "body-md": ["Inter"],
        "label-md": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "headline-lg": ["Inter"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};
